### ISSUE TITLE
unable to create conda environment

### ISSUE THREAD

**Issue by zihhuafang** [WGLab/PhenoSV#1]
Hi, 

I was trying to install PhenoSV following the instruction in README but have encountered the issue to create conda environment when running `conda env create --name phenosv --file phenosv.yml`
It seems like the packages in the phenosv.yml are incompatible.

Solving environment: -
Found conflicts! Looking for incompatible packages.
Could not solve for environment specs
The following packages are incompatible
├─ pybedtools 0.9.0**  is installable with the potential options
│  ├─ pybedtools 0.9.0 would require
│  │  └─ libgcc-ng >=12 , which conflicts with any installable versions previously reported;
│  ├─ pybedtools 0.9.0 would require
│  │  └─ python >=3.6,<3.7.0a0  with the potential options
│  │     ├─ python [3.6.0|3.6.1|...|3.6.9], which can be installed;
│  │     └─ python [3.6.7|3.7.1] would require
│  │        └─ openssl >=1.1.1,<1.1.2.0a0 , which does not exist (perhaps a missing channel);
│  ├─ pybedtools 0.9.0 would require
│  │  └─ python >=3.7,<3.8.0a0  with the potential options
│  │     ├─ python [3.6.7|3.7.1], which cannot be installed (as previously explained);
│  │     └─ python [3.7.0|3.7.1|...|3.7.9], which can be installed;
│  ├─ pybedtools 0.9.0 would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  └─ pybedtools 0.9.0 would require
│     └─ python >=3.9,<3.10.0a0 , which can be installed;
├─ pysam 0.19.1**  is uninstallable because there are no viable options
│  ├─ pysam 0.19.1 would require
│  │  └─ libdeflate >=1.13,<1.14.0a0 , which conflicts with any installable versions previously reported;
│  └─ pysam 0.19.1 would require
│     └─ libdeflate >=1.10,<1.11.0a0 , which conflicts with any installable versions previously reported;
├─ python 3.10.4**  is uninstallable because it conflicts with any installable versions previously reported;
├─ pytorch-lightning 1.6.4**  is uninstallable because it conflicts with any installable versions previously reported;
├─ tensorboard 2.10.1**  is uninstallable because it conflicts with any installable versions previously reported;
└─ torchmetrics 0.10.0**  is uninstallable because it conflicts with any installable versions previously reported.

I attached a more detailed log of the package conflicts here.
[conda.log](https://github.com/WGLab/PhenoSV/files/13661408/conda.log)

Is there a possible fix for the version of packages?
Thank you.
Zih-Hua

**Comment by kaichop** [comment]
Are you using Apple M1 chip? It is not supported because many packages do
not have binary for M1.
Also you may want to upgrade your conda environment and see if it solves
the problem.

**Comment by zihhuafang** [comment]
No, it's Linux environment.

I have tried freshly installed miniconda based on README, but it returned the same error.
`wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh`
`bash Miniconda3-latest-Linux-x86_64.sh`
`conda env create --name phenosv --file phenosv.yml`

I also tried conda update by running `conda update conda` followed by `conda env create --name phenosv --file phenosv.yml`

Any other suggestions for the fix or troubleshooting?
Thank you very much.

**Comment by kaichop** [comment]
The log file seems to show that your conda version is 2.28. The current most updated version is 23.11. Are you sure you have updated conda to the latest version? The version 2.28 is really old.

**Comment by zihhuafang** [comment]
My conda version was 23.11.0 after I freshly installed miniconda as I checked by `conda -V`. 
I figured out the problem was conda channel priority.
After I ran `conda config --set channel_priority true`, I was able to create conda environment by running `conda env create --name phenosv --file phenosv.yml`

**Comment by kaichop** [comment]
Thank you!
