### ISSUE TITLE
Why is PhenoSV score always `0.0`?

### ISSUE THREAD

**Issue by jsquaredosquared** [WGLab/PhenoSV#10]
Hi,

I have tried to score the examples in the README using PhenoSV-light, but the Phen2Gene and PhenoSV scores are always 0. What could be the reason for this? 

I would appreciate your guidance.
Thanks

```bash
python phenosv/model/phenosv.py --model PhenoSV-light \
--c chr6 --s 156994830 --e 157006982 --svtype 'deletion' \
--noncoding 'tad' \
--HPO 'HP:0000707,HP:0007598'

  Elements  Pathogenicity           Type  Phen2Gene  PhenoSV
0       SV       0.607864  Non-coding SV          0      0.0
1   ARID1B       0.550785       Intronic          0      0.0
2     NOX3       0.155716     Regulatory          0      0.0
3    TFB1M       0.249238     Regulatory          0      0.0
```

**Comment by Karenxzr** [comment]
> Hi,
> 
> I have tried to score the examples in the README using PhenoSV-light, but the Phen2Gene and PhenoSV scores are always 0. What could be the reason for this?
> 
> I would appreciate your guidance. Thanks
> 
> ```shell
> python phenosv/model/phenosv.py --model PhenoSV-light \
> --c chr6 --s 156994830 --e 157006982 --svtype 'deletion' \
> --noncoding 'tad' \
> --HPO 'HP:0000707,HP:0007598'
> 
>   Elements  Pathogenicity           Type  Phen2Gene  PhenoSV
> 0       SV       0.607864  Non-coding SV          0      0.0
> 1   ARID1B       0.550785       Intronic          0      0.0
> 2     NOX3       0.155716     Regulatory          0      0.0
> 3    TFB1M       0.249238     Regulatory          0      0.0
> ```

Hi, it is because genes that the given SV affected doesn’t show any associations with given HPO terms based on phen2gene.

**Comment by jsquaredosquared** [comment]
But according to the [example in the README](https://github.com/WGLab/PhenoSV#example2), there should be some association?

```
  Elements  Pathogenicity           Type  Phen2Gene   PhenoSV
0       SV       0.664912  Non-coding SV   0.999126  0.664331
1   ARID1B       0.823556       Intronic   0.999126  0.822836
2     NOX3       0.045648     Regulatory   0.837460  0.038229
3    TFB1M       0.533431     Regulatory   0.544762  0.290593
```

When I score variants using the web tool, there is an association. But when I use the CLI, the values are always 0.

**Comment by Karenxzr** [comment]
It's working well on my end. Can you double confirm the data file for phen2gene has been installed correctly? (knowledgebase, skewness, weights)
<img width="1155" alt="image" src="https://github.com/WGLab/PhenoSV/assets/27308407/2ac0550b-45bc-4998-85bc-e22fd4ab8d39">
<img width="386" alt="image" src="https://github.com/WGLab/PhenoSV/assets/27308407/bcd3009c-a0fc-44cc-961a-f2812eec16df">

**Comment by 17student34** [comment]
I forgot to unzip the file 🤦

Thanks for your help 🙂

**Comment by jsquaredosquared** [comment]
I forgot to unzip the file 🤦

It works now.

Thanks for your help 🙂
