### ISSUE TITLE
Missing `features_set.csv` file

### ISSUE THREAD

**Issue by corinsexton** [WGLab/PhenoSV#13]
Hi there,

I just installed PhenoSV and my first run is showing that the `features_set.csv` file is missing. I used the command to download the full model using `setup.sh` which completed successfully. It looks like the rest of the files are in the directory. What's the best way for me to download this file?

```
FileNotFoundError: [Errno 2] No such file or directory: '/phenosv_data/data/features_set.csv'
```
Here's the contents of the `data` directory:
<img width="1346" alt="data dir" src="https://github.com/user-attachments/assets/c92866e5-86d2-465c-afe7-2956f6a51b7c">

Thank you,

Corinne

**Comment by Karenxzr** [comment]
Hi Corinne, I see you have `features_set_light.csv` there but missing `features_set.csv`. There may be a problem when you trying to run setup.sh. However, I think you can manually make a copy of `featuremaster_scu1026.csv` (fig1 below), and change the root folder paths to your folder storing all features (fig2 below where my data locates at /Volumes/G-DRIVE USB-C/...). This should be similar with `features_set_light.csv` 

Alternatively, you can rerun the script of `python3 $current_dir/phenosv/setup.py --path "$fpath/data"` to create `features_set.csv` for setting up the path.

Please let me know if it works.

<img width="800" alt="image" src="https://github.com/user-attachments/assets/f12042e7-c3d2-458f-a063-04f486f4966b">
<img width="800" alt="image" src="https://github.com/user-attachments/assets/931d063d-f43f-44f9-95ca-0ac88d8c3f08">

**Comment by corinsexton** [comment]
Looks like the issue was in the last line of `setup.sh`.

```
python3 $current_dir/phenosv/setup.py --path "$fpath/data"
```

I wasn't in the correct conda environment and this part was dropped. Rerunning that last line fixed it. Thanks!
