### ISSUE TITLE
Insertion marked as "Exonic" but start position is in an Intron

### ISSUE THREAD

**Issue by MariosGvr** [WGLab/PhenoSV#2]
Hi,
thank you for the incredible tool!

While reviewing my results table, I noticed that certain insertions marked as exonic actually start in an intronic position. Considering both the start and end positions, these insertions potentially "cover" an exonic region.

However, in my understanding, an insertion that begins in an intron should be classified as intronic, as it "pushes" the exon further away rather than spanning it. Is there a specific notion behind which PhenoSV marks those insertions as exonic?

I'm using the terminal version of the PhenoSV tool for annotating multiple SVs, and the web version gives me the same results.

Example:
```
chrom	start		end		length	svtype		Elements	Type
chr14	39064016	39067194	3178	insertion	SEC23A		Exonic
```
Start position on an intronic region:
![image](https://github.com/WGLab/PhenoSV/assets/101292511/30fc9cb7-2910-45d7-a6ae-e64ab66512ef)

Range of SV (Start position marked with the blue line, SV spans on the right):
![image](https://github.com/WGLab/PhenoSV/assets/101292511/8bd95878-0f32-467e-a78b-bda93ffe2037)

Thank you!

**Comment by kaichop** [comment]
If it is just an insertion at a location, then the start and end needs to
be identical to each other. Here you have a 3.2kb genomic region in the
file, and this is not an insertion. Clearly this region covers exons.

**Comment by MariosGvr** [comment]
Thank you very much for your input!
I was able to work around the issue.
