### ISSUE TITLE
Feature Array has size of 0?

### ISSUE THREAD

**Issue by mjang2000** [WGLab/PhenoSV#8]
Hello, I'm running the program for the first time in Python and there is a ValueError for the basic running of the algorithm becaus of a size 0 feature array.

<img width="541" alt="Screenshot 2024-04-14 at 11 15 19 PM" src="https://github.com/WGLab/PhenoSV/assets/43710235/4b47b04b-3fc7-405f-924c-13319e2db913">

Can you help identify what went wrong?

**Comment by Karenxzr** [comment]
Hi, it seems the error lies in configuring file location. Can you double confirm the 'config_path' is the right place for storing all the files?

**Comment by mjang2000** [comment]
Config has all the correct pathways for all the file names. I manually edited the config because the initiation function didn't work with my file tree

<img width="977" alt="Screenshot 2024-04-15 at 1 54 15 PM" src="https://github.com/WGLab/PhenoSV/assets/43710235/9ed10ac5-620e-40ec-8b43-e1e27963ed69">

Although "../phenosv_files/data/chromhmm_15.bb" does not exist. How can I change this to "/home/amyjang/phenosv_files/data/chromhmm_15.bb"?

**Comment by Karenxzr** [comment]
Try running scripts in 'phenosv/setup.py', which basically change the file paths in the csv files of feature_files and scaler_file.

**Comment by mjang2000** [comment]
@Karenxzr that worked thanks!

I'm trying to replicate this in the terminal, and I get the following error?
![image](https://github.com/WGLab/PhenoSV/assets/43710235/75e6eb85-3f68-4426-b9b9-b4f55999ee04)

The notebook cell worked fine, and the csv file is formatted correctly based on the sample datasets provided.

**Comment by mjang2000** [comment]
Hi team, bumping this in case it was missed.

**Comment by Karenxzr** [comment]
Can you try to score the given sampledata.csv? It works well on my end. 

<img width="690" alt="image" src="https://github.com/WGLab/PhenoSV/assets/27308407/a05c00bd-bfd6-4d64-8c14-e3ebed4b4347">

**Comment by Karenxzr** [comment]
@mjang2000 The error might be caused by SVs on chromosomes as mentioned in #9 . I fixed the bug, please pull and try it again.
