### ISSUE TITLE
Processing a large number of sv

### ISSUE THREAD

**Issue by realmanlxw** [WGLab/PhenoSV#9]
Hello, a great job, I tried to use your tools. There are no problems running 10 SVs, but I will report an error when I have more than 3,000 SV. What is the SV of this tool at the same time? This command is running: Bash Phenosv/Model/Phenosv.sh 'Path/to/SV/Data.csv' 'Folder/PATH/TO/Store/Results' 4. And the error is the picture below：Very much looking forward to your reply.
![419f13aef563dbf6ee6c78b68d42699](https://github.com/WGLab/PhenoSV/assets/122415607/b0703adf-a022-48ca-a2d2-4536561b6673)

**Comment by Karenxzr** [comment]
Hi, thank you for your interest. Have you tried scoring the sample data of 'data/sampledata.csv'?

**Comment by realmanlxw** [comment]
Yes, the sample data is totally fine, even if I take some of my 3000+ sv's it's fine

**Comment by Karenxzr** [comment]
I guess the error is cause by specific SVs in your csv file. Can you identify which one? Alternatively, I can help look into it if you can send me your csv file.

**Comment by realmanlxw** [comment]
[output.csv](https://github.com/WGLab/PhenoSV/files/15041486/output.csv)
This is my sv data, you can use it as a reference

**Comment by Karenxzr** [comment]
There are many SVs on sex chromosome that PhenoSV did not treat them as valid. I fixed the bug now. Please pull and test. Let me know if it works this time, thank you!

**Comment by realmanlxw** [comment]
Hello, the task has been completed, thank you for your correction.

**Comment by poddarharsh15** [comment]
> Hello, a great job, I tried to use your tools. There are no problems running 10 SVs, but I will report an error when I have more than 3,000 SV. What is the SV of this tool at the same time? This command is running: Bash Phenosv/Model/Phenosv.sh 'Path/to/SV/Data.csv' 'Folder/PATH/TO/Store/Results' 4. And the error is the picture below：Very much looking forward to your reply. ![419f13aef563dbf6ee6c78b68d42699](https://private-user-images.githubusercontent.com/122415607/323969459-b0703adf-a022-48ca-a2d2-4536561b6673.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDM4MzUsIm5iZiI6MTcyNzQ0MzUzNSwicGF0aCI6Ii8xMjI0MTU2MDcvMzIzOTY5NDU5LWIwNzAzYWRmLWEwMjItNDhjYS1hMmQyLTQ1MzY1NjFiNjY3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxMzI1MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTViMWNjNzhmZDRiNDhjYThhODFlNmZmYWM3YzM5ODQ3MzU4Mzc3MWUzMGFiZGRjZDI2YzU0NTlkODEwNjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IcqbZYP8q-dI87RYYg_xHlSRCubHypL0w8aV4Ca_Tag)

Hi @realmanlxw,

Apologies for opening this thread here. I noticed you have experience manipulating VCF files to create BED or CSV formats for PhenoSV analysis. Could you please suggest some tools or methods that you use for this process? Any guidance or recommendations would be highly appreciated.

Thank you in advance for your help!
